// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOFuZ31FlaTEaLQTsSmgfopkc0nzknAIM',
    appId: '1:130690398592:web:deb329562a5fbd2106e965',
    messagingSenderId: '130690398592',
    projectId: 'clauselens-81eb8',
    authDomain: 'clauselens-81eb8.firebaseapp.com',
    storageBucket: 'clauselens-81eb8.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOFuZ31FlaTEaLQTsSmgfopkc0nzknAIM',
    appId: '1:130690398592:android:deb329562a5fbd2106e965',
    messagingSenderId: '130690398592',
    projectId: 'clauselens-81eb8',
    authDomain: 'clauselens-81eb8.firebaseapp.com',
    storageBucket: 'clauselens-81eb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOFuZ31FlaTEaLQTsSmgfopkc0nzknAIM',
    appId: '1:130690398592:ios:deb329562a5fbd2106e965',
    messagingSenderId: '130690398592',
    projectId: 'clauselens-81eb8',
    authDomain: 'clauselens-81eb8.firebaseapp.com',
    storageBucket: 'clauselens-81eb8.firebasestorage.app',
    iosBundleId: 'com.example.clauselens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOFuZ31FlaTEaLQTsSmgfopkc0nzknAIM',
    appId: '1:130690398592:ios:deb329562a5fbd2106e965',
    messagingSenderId: '130690398592',
    projectId: 'clauselens-81eb8',
    authDomain: 'clauselens-81eb8.firebaseapp.com',
    storageBucket: 'clauselens-81eb8.firebasestorage.app',
    iosBundleId: 'com.example.clauselens',
  );
}
